### PR TITLE
Description of how to cite the software

### LINKED ISSUE #89: Add information about how to cite software
As part of the #83 PR, @arfon brought up the point that we should [add information about how to cite the software](https://github.com/spacetelescope/style-guides/pull/83#issuecomment-462850699). 

So, a PR should be put in that adds information about how to cite the software (e.g., bibtex), and/or a `__citation__` method, and/or a `CITATION` file.

### PR DESCRIPTION
**Pull request by brechmos-stsci**
Descriptions were added of how to cite the software repo for journal articles etc. 

Fixes #89

### CODE REVIEW

**Comment by arfon** [comment]
@brechmos-stsci - is this PR still a work in progress?

**Comment by brechmos-stsci** [comment]
It is. I have been in class all week so have not been working on it.

**Comment by brechmos-stsci** [comment]
I talked with @arfon about what we should suggest here and what astropy is doing probably makes the most sense.  So, this PR is to formalize that.  
@arfon @stscicrawford Feel free to review

**Comment by brechmos-stsci** [comment]
@arfon Ummm.... I think that is duplicating information in the `CITATION` file, no?  I can maybe see adding a comment in the `software-versioning.md` in the `Citing Software` section to say that the `README` file should include a short paragraph  to see the `CITATION` file and include the zenodo badge.  

The current thought is that the `CITATION` file contains the bibtex entry etc, so don't want to duplicate that info in the `README` file.

**Comment by arfon** [comment]
> @arfon Ummm.... I think that is duplicating information in the `CITATION` file, no? 

Yes, but I come from the school of _make it as easy as possible for people to do the right thing_ 😁.

>  I can maybe see adding a comment in the `software-versioning.md` in the `Citing Software` section to say that the `README` file should include a short paragraph to see the `CITATION` file and include the zenodo badge.  

👍 that sounds like a good option to me.

**Comment by arfon** [comment]
:wave: @brechmos-stsci - is this ready to ship?

**Comment by brechmos-stsci** [comment]
Yes, I believe it is good to go, if you are good with it.

**Comment by arfon** [comment]
:shipit:

**Comment by arfon** [comment]
🎉

**Pull request merged**
